language: python
python:
  - 3.6

os: linux

stages:
  - name: publish
    # Don't run build stage for pull requests and other branches than master
    # to save time and resources.
    if: (branch = master OR tag IS present)

services:
  - docker

before_install:
  - sudo apt-get -y install jq

install:
  - docker build -t cgwire/cgwire .
  - docker run --init -d -p 80:80 --name cgwire cgwire/cgwire


# deploy:
#   provider: script
#   script: bash docker_push
#   on:
#     tags: true
#     branch: master
#     condition: '"${DEPLOY:-0}" -eq 1'

jobs:
  include:
    - name: "Build with Ubuntu Bionic"
      dist: bionic
    - name: "Build with Ubuntu Focal"
      dist: focal
      env: DEPLOY=1

script:
  - docker ps | grep -q cgwire
  - pip3 install httpie
  - http localhost:80/api | grep Zou
  - http localhost:80 | grep Kitsu
  - http POST localhost:80/api/auth/login email=admin@example.com password=mysecretpassword
  - http POST localhost:80/api/auth/login email=admin@example.com password=mysecretpassword | jq --exit-status 'select(.error != true)'
  - http POST localhost:80/api/auth/login email=admin@example.com password=mysecretpassword | jq --exit-status 'select(.login == true)'
  - http POST localhost:80/api/auth/login email=admin@example.com password=wrongpassword | jq --exit-status 'select(.login == false)'
  - http POST localhost:80/api/auth/login email=missing@example.com password=wrongpassword | jq --exit-status 'select(.login == false)'
  - http POST localhost:80/api/auth/login email=admin@example.com password=mysecretpassword | jq .login 
